### ISSUE TITLE
Test with Local Machine ?

### ISSUE THREAD

**Issue by 1unknwn** [GoogleCloudPlatform/immersive-stream-for-xr-templates#12]
Can I test Local Machine as VM before deployingto GCP ?

**Comment by wochanda** [comment]
Hi - you can currently preview your experience inside Unreal Engine to validate look, feel, and functionality. We don't support using your local machine as an endpoint to connect to from another device (like your phone). For this, you need to deploy to the Immersive Stream for XR service.
