### ISSUE TITLE
Cardboard VR ?

### ISSUE THREAD

**Issue by EONWorks** [GoogleCloudPlatform/immersive-stream-for-xr-templates#2]
There are input keys for controller and that's great. Will it work for Cardboard VR like stereoscopic rendering and headtracking in mobile devices. And Google and android team has deprecated Cardboard-vr support for Unreal Engine. How it will work ?

**Comment by flobotics** [comment]
are there any news about it ? or is immersive-stream-xr project faster dying than other google projects :)

**Comment by wochanda** [comment]
We don't currently support stereoscoping rendering for Cardboard or other VR headsets. If that changes in the future you'll see an update to this project and to the Immersive Stream for XR documentation.

**Comment by flobotics** [comment]
thanks, just a question, what do you support and what it is for then ?  XR ?  cellphones got rear-camera for XR in cardboard, or VR headsets like pico-3 and pico-4 got rgb-camera for XR? sorry, but i dont understand for what is it?
